FROM node:6

# make the src folder available in the docker image
ADD src/ /src
ADD package.json /src
WORKDIR /src

# install the dependencies from the package.json file
RUN npm install

# make port 5000 available outside of the image
EXPOSE 5000

# start node with the index.js file of our hello-world application
CMD ["node", "mothership.js"]
